// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$Heartbeat { bool gps_pos_valid; bool maint_reqd; bool ident; bool addr_type; bool gps_batt_low; bool ratcs; bool uat_initialized; bool csa_requested; bool csa_not_available; bool utc_ok; uint32_t timestamp; uint16_t message_counts; } __swift_bridge__$Heartbeat;
typedef struct __swift_bridge__$Option$Heartbeat { bool is_some; __swift_bridge__$Heartbeat val; } __swift_bridge__$Option$Heartbeat;
typedef struct __swift_bridge__$Initialization { bool audio_test; bool audio_inhibit; bool cdti_ok; bool csa_audio_disable; bool csa_disable; } __swift_bridge__$Initialization;
typedef struct __swift_bridge__$Option$Initialization { bool is_some; __swift_bridge__$Initialization val; } __swift_bridge__$Option$Initialization;
typedef enum __swift_bridge__$TrafficAlertStatusTag { __swift_bridge__$TrafficAlertStatus$NoAlert, __swift_bridge__$TrafficAlertStatus$TrafficAlert, } __swift_bridge__$TrafficAlertStatusTag;
typedef struct __swift_bridge__$TrafficAlertStatus { __swift_bridge__$TrafficAlertStatusTag tag; } __swift_bridge__$TrafficAlertStatus;
typedef struct __swift_bridge__$Option$TrafficAlertStatus { bool is_some; __swift_bridge__$TrafficAlertStatus val; } __swift_bridge__$Option$TrafficAlertStatus;

void* __swift_bridge__$Vec_TrafficAlertStatus$new(void);
void __swift_bridge__$Vec_TrafficAlertStatus$drop(void* vec_ptr);
void __swift_bridge__$Vec_TrafficAlertStatus$push(void* vec_ptr, __swift_bridge__$TrafficAlertStatus item);
__swift_bridge__$Option$TrafficAlertStatus __swift_bridge__$Vec_TrafficAlertStatus$pop(void* vec_ptr);
__swift_bridge__$Option$TrafficAlertStatus __swift_bridge__$Vec_TrafficAlertStatus$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$TrafficAlertStatus __swift_bridge__$Vec_TrafficAlertStatus$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_TrafficAlertStatus$len(void* vec_ptr);
void* __swift_bridge__$Vec_TrafficAlertStatus$as_ptr(void* vec_ptr);

typedef enum __swift_bridge__$AddressTypeTag { __swift_bridge__$AddressType$AdsbIcao, __swift_bridge__$AddressType$AdsbSelfAssigned, __swift_bridge__$AddressType$TisbIcao, __swift_bridge__$AddressType$TisbTrackFileId, __swift_bridge__$AddressType$SurfaceVehicle, __swift_bridge__$AddressType$GroundStationBeacon, } __swift_bridge__$AddressTypeTag;
typedef struct __swift_bridge__$AddressType { __swift_bridge__$AddressTypeTag tag; } __swift_bridge__$AddressType;
typedef struct __swift_bridge__$Option$AddressType { bool is_some; __swift_bridge__$AddressType val; } __swift_bridge__$Option$AddressType;

void* __swift_bridge__$Vec_AddressType$new(void);
void __swift_bridge__$Vec_AddressType$drop(void* vec_ptr);
void __swift_bridge__$Vec_AddressType$push(void* vec_ptr, __swift_bridge__$AddressType item);
__swift_bridge__$Option$AddressType __swift_bridge__$Vec_AddressType$pop(void* vec_ptr);
__swift_bridge__$Option$AddressType __swift_bridge__$Vec_AddressType$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$AddressType __swift_bridge__$Vec_AddressType$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_AddressType$len(void* vec_ptr);
void* __swift_bridge__$Vec_AddressType$as_ptr(void* vec_ptr);

typedef struct __swift_bridge__$TargetIdentity { struct __swift_bridge__$AddressType address_type; uint32_t participant_address; } __swift_bridge__$TargetIdentity;
typedef struct __swift_bridge__$Option$TargetIdentity { bool is_some; __swift_bridge__$TargetIdentity val; } __swift_bridge__$Option$TargetIdentity;
typedef enum __swift_bridge__$AirGroundStateTag { __swift_bridge__$AirGroundState$OnGround, __swift_bridge__$AirGroundState$Airborne, } __swift_bridge__$AirGroundStateTag;
typedef struct __swift_bridge__$AirGroundState { __swift_bridge__$AirGroundStateTag tag; } __swift_bridge__$AirGroundState;
typedef struct __swift_bridge__$Option$AirGroundState { bool is_some; __swift_bridge__$AirGroundState val; } __swift_bridge__$Option$AirGroundState;

void* __swift_bridge__$Vec_AirGroundState$new(void);
void __swift_bridge__$Vec_AirGroundState$drop(void* vec_ptr);
void __swift_bridge__$Vec_AirGroundState$push(void* vec_ptr, __swift_bridge__$AirGroundState item);
__swift_bridge__$Option$AirGroundState __swift_bridge__$Vec_AirGroundState$pop(void* vec_ptr);
__swift_bridge__$Option$AirGroundState __swift_bridge__$Vec_AirGroundState$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$AirGroundState __swift_bridge__$Vec_AirGroundState$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_AirGroundState$len(void* vec_ptr);
void* __swift_bridge__$Vec_AirGroundState$as_ptr(void* vec_ptr);

typedef enum __swift_bridge__$ReportTypeTag { __swift_bridge__$ReportType$Updated, __swift_bridge__$ReportType$Extrapolated, } __swift_bridge__$ReportTypeTag;
typedef struct __swift_bridge__$ReportType { __swift_bridge__$ReportTypeTag tag; } __swift_bridge__$ReportType;
typedef struct __swift_bridge__$Option$ReportType { bool is_some; __swift_bridge__$ReportType val; } __swift_bridge__$Option$ReportType;

void* __swift_bridge__$Vec_ReportType$new(void);
void __swift_bridge__$Vec_ReportType$drop(void* vec_ptr);
void __swift_bridge__$Vec_ReportType$push(void* vec_ptr, __swift_bridge__$ReportType item);
__swift_bridge__$Option$ReportType __swift_bridge__$Vec_ReportType$pop(void* vec_ptr);
__swift_bridge__$Option$ReportType __swift_bridge__$Vec_ReportType$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$ReportType __swift_bridge__$Vec_ReportType$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_ReportType$len(void* vec_ptr);
void* __swift_bridge__$Vec_ReportType$as_ptr(void* vec_ptr);

typedef enum __swift_bridge__$TrackHeadingTypeTag { __swift_bridge__$TrackHeadingType$NotValid, __swift_bridge__$TrackHeadingType$TrueTrackAngle, __swift_bridge__$TrackHeadingType$HeadingMagnetic, __swift_bridge__$TrackHeadingType$HeadingTrue, } __swift_bridge__$TrackHeadingTypeTag;
typedef struct __swift_bridge__$TrackHeadingType { __swift_bridge__$TrackHeadingTypeTag tag; } __swift_bridge__$TrackHeadingType;
typedef struct __swift_bridge__$Option$TrackHeadingType { bool is_some; __swift_bridge__$TrackHeadingType val; } __swift_bridge__$Option$TrackHeadingType;

void* __swift_bridge__$Vec_TrackHeadingType$new(void);
void __swift_bridge__$Vec_TrackHeadingType$drop(void* vec_ptr);
void __swift_bridge__$Vec_TrackHeadingType$push(void* vec_ptr, __swift_bridge__$TrackHeadingType item);
__swift_bridge__$Option$TrackHeadingType __swift_bridge__$Vec_TrackHeadingType$pop(void* vec_ptr);
__swift_bridge__$Option$TrackHeadingType __swift_bridge__$Vec_TrackHeadingType$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$TrackHeadingType __swift_bridge__$Vec_TrackHeadingType$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_TrackHeadingType$len(void* vec_ptr);
void* __swift_bridge__$Vec_TrackHeadingType$as_ptr(void* vec_ptr);

typedef struct __swift_bridge__$MiscellaneousIndicators { struct __swift_bridge__$AirGroundState air_ground_state; struct __swift_bridge__$ReportType report_type; struct __swift_bridge__$TrackHeadingType track_heading_type; } __swift_bridge__$MiscellaneousIndicators;
typedef struct __swift_bridge__$Option$MiscellaneousIndicators { bool is_some; __swift_bridge__$MiscellaneousIndicators val; } __swift_bridge__$Option$MiscellaneousIndicators;
typedef enum __swift_bridge__$NICTag { __swift_bridge__$NIC$NIC0_Unknown, __swift_bridge__$NIC$NIC1_20NM, __swift_bridge__$NIC$NIC2_8NM, __swift_bridge__$NIC$NIC3_4NM, __swift_bridge__$NIC$NIC4_2NM, __swift_bridge__$NIC$NIC5_1NM, __swift_bridge__$NIC$NIC6_0_6NM, __swift_bridge__$NIC$NIC7_0_2NM, __swift_bridge__$NIC$NIC8_0_1NM, __swift_bridge__$NIC$NIC9_HPL_75M_VPL_112M, __swift_bridge__$NIC$NIC10_HPL_25M_VPL_37_5M, __swift_bridge__$NIC$NIC11_HPL_7_5M_VPL_11M, } __swift_bridge__$NICTag;
typedef struct __swift_bridge__$NIC { __swift_bridge__$NICTag tag; } __swift_bridge__$NIC;
typedef struct __swift_bridge__$Option$NIC { bool is_some; __swift_bridge__$NIC val; } __swift_bridge__$Option$NIC;

void* __swift_bridge__$Vec_NIC$new(void);
void __swift_bridge__$Vec_NIC$drop(void* vec_ptr);
void __swift_bridge__$Vec_NIC$push(void* vec_ptr, __swift_bridge__$NIC item);
__swift_bridge__$Option$NIC __swift_bridge__$Vec_NIC$pop(void* vec_ptr);
__swift_bridge__$Option$NIC __swift_bridge__$Vec_NIC$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$NIC __swift_bridge__$Vec_NIC$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_NIC$len(void* vec_ptr);
void* __swift_bridge__$Vec_NIC$as_ptr(void* vec_ptr);

typedef enum __swift_bridge__$NACpTag { __swift_bridge__$NACp$NACp0_Unknown, __swift_bridge__$NACp$NACp1_10NM, __swift_bridge__$NACp$NACp2_4NM, __swift_bridge__$NACp$NACp3_2NM, __swift_bridge__$NACp$NACp4_1NM, __swift_bridge__$NACp$NACp5_0_5NM, __swift_bridge__$NACp$NACp6_0_3NM, __swift_bridge__$NACp$NACp7_0_1NM, __swift_bridge__$NACp$NACp8_0_05NM, __swift_bridge__$NACp$NACp9_HFOM_30M_VFOM_45M, __swift_bridge__$NACp$NACp10_HFOM_10M_VFOM_15M, __swift_bridge__$NACp$NACp11_HFOM_3M_VFOM_4M, } __swift_bridge__$NACpTag;
typedef struct __swift_bridge__$NACp { __swift_bridge__$NACpTag tag; } __swift_bridge__$NACp;
typedef struct __swift_bridge__$Option$NACp { bool is_some; __swift_bridge__$NACp val; } __swift_bridge__$Option$NACp;

void* __swift_bridge__$Vec_NACp$new(void);
void __swift_bridge__$Vec_NACp$drop(void* vec_ptr);
void __swift_bridge__$Vec_NACp$push(void* vec_ptr, __swift_bridge__$NACp item);
__swift_bridge__$Option$NACp __swift_bridge__$Vec_NACp$pop(void* vec_ptr);
__swift_bridge__$Option$NACp __swift_bridge__$Vec_NACp$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$NACp __swift_bridge__$Vec_NACp$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_NACp$len(void* vec_ptr);
void* __swift_bridge__$Vec_NACp$as_ptr(void* vec_ptr);

typedef enum __swift_bridge__$EmitterCategoryTag { __swift_bridge__$EmitterCategory$NoInformation, __swift_bridge__$EmitterCategory$Light, __swift_bridge__$EmitterCategory$Small, __swift_bridge__$EmitterCategory$Large, __swift_bridge__$EmitterCategory$HighVortexLarge, __swift_bridge__$EmitterCategory$Heavy, __swift_bridge__$EmitterCategory$HighlyManeuverable, __swift_bridge__$EmitterCategory$Rotorcraft, __swift_bridge__$EmitterCategory$GliderSailplane, __swift_bridge__$EmitterCategory$LighterThanAir, __swift_bridge__$EmitterCategory$ParachutistSkyDiver, __swift_bridge__$EmitterCategory$UltraLightHangGliderParaglider, __swift_bridge__$EmitterCategory$UnmannedAerialVehicle, __swift_bridge__$EmitterCategory$SpaceTransatmosphericVehicle, __swift_bridge__$EmitterCategory$SurfaceVehicleEmergencyVehicle, __swift_bridge__$EmitterCategory$SurfaceVehicleServiceVehicle, __swift_bridge__$EmitterCategory$PointObstacleIncludesTetheredBalloons, __swift_bridge__$EmitterCategory$ClusterObstacle, __swift_bridge__$EmitterCategory$LineObstacle, } __swift_bridge__$EmitterCategoryTag;
typedef struct __swift_bridge__$EmitterCategory { __swift_bridge__$EmitterCategoryTag tag; } __swift_bridge__$EmitterCategory;
typedef struct __swift_bridge__$Option$EmitterCategory { bool is_some; __swift_bridge__$EmitterCategory val; } __swift_bridge__$Option$EmitterCategory;

void* __swift_bridge__$Vec_EmitterCategory$new(void);
void __swift_bridge__$Vec_EmitterCategory$drop(void* vec_ptr);
void __swift_bridge__$Vec_EmitterCategory$push(void* vec_ptr, __swift_bridge__$EmitterCategory item);
__swift_bridge__$Option$EmitterCategory __swift_bridge__$Vec_EmitterCategory$pop(void* vec_ptr);
__swift_bridge__$Option$EmitterCategory __swift_bridge__$Vec_EmitterCategory$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$EmitterCategory __swift_bridge__$Vec_EmitterCategory$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_EmitterCategory$len(void* vec_ptr);
void* __swift_bridge__$Vec_EmitterCategory$as_ptr(void* vec_ptr);

typedef enum __swift_bridge__$EmergencyPriorityCodeTag { __swift_bridge__$EmergencyPriorityCode$NoEmergency, __swift_bridge__$EmergencyPriorityCode$GeneralEmergency, __swift_bridge__$EmergencyPriorityCode$MedicalEmergency, __swift_bridge__$EmergencyPriorityCode$MinimumFuel, __swift_bridge__$EmergencyPriorityCode$NoCommunication, __swift_bridge__$EmergencyPriorityCode$UnlawfulInterference, __swift_bridge__$EmergencyPriorityCode$DownedAircraft, } __swift_bridge__$EmergencyPriorityCodeTag;
typedef struct __swift_bridge__$EmergencyPriorityCode { __swift_bridge__$EmergencyPriorityCodeTag tag; } __swift_bridge__$EmergencyPriorityCode;
typedef struct __swift_bridge__$Option$EmergencyPriorityCode { bool is_some; __swift_bridge__$EmergencyPriorityCode val; } __swift_bridge__$Option$EmergencyPriorityCode;

void* __swift_bridge__$Vec_EmergencyPriorityCode$new(void);
void __swift_bridge__$Vec_EmergencyPriorityCode$drop(void* vec_ptr);
void __swift_bridge__$Vec_EmergencyPriorityCode$push(void* vec_ptr, __swift_bridge__$EmergencyPriorityCode item);
__swift_bridge__$Option$EmergencyPriorityCode __swift_bridge__$Vec_EmergencyPriorityCode$pop(void* vec_ptr);
__swift_bridge__$Option$EmergencyPriorityCode __swift_bridge__$Vec_EmergencyPriorityCode$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$EmergencyPriorityCode __swift_bridge__$Vec_EmergencyPriorityCode$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_EmergencyPriorityCode$len(void* vec_ptr);
void* __swift_bridge__$Vec_EmergencyPriorityCode$as_ptr(void* vec_ptr);

typedef enum __swift_bridge__$ForeFlightInternetPolicyTag { __swift_bridge__$ForeFlightInternetPolicy$Unrestricted, __swift_bridge__$ForeFlightInternetPolicy$Expensive, __swift_bridge__$ForeFlightInternetPolicy$Disallowed, } __swift_bridge__$ForeFlightInternetPolicyTag;
typedef struct __swift_bridge__$ForeFlightInternetPolicy { __swift_bridge__$ForeFlightInternetPolicyTag tag; } __swift_bridge__$ForeFlightInternetPolicy;
typedef struct __swift_bridge__$Option$ForeFlightInternetPolicy { bool is_some; __swift_bridge__$ForeFlightInternetPolicy val; } __swift_bridge__$Option$ForeFlightInternetPolicy;

void* __swift_bridge__$Vec_ForeFlightInternetPolicy$new(void);
void __swift_bridge__$Vec_ForeFlightInternetPolicy$drop(void* vec_ptr);
void __swift_bridge__$Vec_ForeFlightInternetPolicy$push(void* vec_ptr, __swift_bridge__$ForeFlightInternetPolicy item);
__swift_bridge__$Option$ForeFlightInternetPolicy __swift_bridge__$Vec_ForeFlightInternetPolicy$pop(void* vec_ptr);
__swift_bridge__$Option$ForeFlightInternetPolicy __swift_bridge__$Vec_ForeFlightInternetPolicy$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$ForeFlightInternetPolicy __swift_bridge__$Vec_ForeFlightInternetPolicy$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_ForeFlightInternetPolicy$len(void* vec_ptr);
void* __swift_bridge__$Vec_ForeFlightInternetPolicy$as_ptr(void* vec_ptr);

typedef enum __swift_bridge__$GeometricAltitudeDatumTag { __swift_bridge__$GeometricAltitudeDatum$WGS84, __swift_bridge__$GeometricAltitudeDatum$MSL, } __swift_bridge__$GeometricAltitudeDatumTag;
typedef struct __swift_bridge__$GeometricAltitudeDatum { __swift_bridge__$GeometricAltitudeDatumTag tag; } __swift_bridge__$GeometricAltitudeDatum;
typedef struct __swift_bridge__$Option$GeometricAltitudeDatum { bool is_some; __swift_bridge__$GeometricAltitudeDatum val; } __swift_bridge__$Option$GeometricAltitudeDatum;

void* __swift_bridge__$Vec_GeometricAltitudeDatum$new(void);
void __swift_bridge__$Vec_GeometricAltitudeDatum$drop(void* vec_ptr);
void __swift_bridge__$Vec_GeometricAltitudeDatum$push(void* vec_ptr, __swift_bridge__$GeometricAltitudeDatum item);
__swift_bridge__$Option$GeometricAltitudeDatum __swift_bridge__$Vec_GeometricAltitudeDatum$pop(void* vec_ptr);
__swift_bridge__$Option$GeometricAltitudeDatum __swift_bridge__$Vec_GeometricAltitudeDatum$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$GeometricAltitudeDatum __swift_bridge__$Vec_GeometricAltitudeDatum$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_GeometricAltitudeDatum$len(void* vec_ptr);
void* __swift_bridge__$Vec_GeometricAltitudeDatum$as_ptr(void* vec_ptr);

typedef struct __swift_bridge__$ForeFlightID { uint8_t version; uint64_t device_serial_number; void* device_name; void* device_long_name; struct __swift_bridge__$ForeFlightInternetPolicy foreflight_internet_policy; struct __swift_bridge__$GeometricAltitudeDatum geometric_altitude_datum; } __swift_bridge__$ForeFlightID;
typedef struct __swift_bridge__$Option$ForeFlightID { bool is_some; __swift_bridge__$ForeFlightID val; } __swift_bridge__$Option$ForeFlightID;
typedef enum __swift_bridge__$AHRSHeadingTypeTag { __swift_bridge__$AHRSHeadingType$True, __swift_bridge__$AHRSHeadingType$Magnetic, } __swift_bridge__$AHRSHeadingTypeTag;
typedef struct __swift_bridge__$AHRSHeadingType { __swift_bridge__$AHRSHeadingTypeTag tag; } __swift_bridge__$AHRSHeadingType;
typedef struct __swift_bridge__$Option$AHRSHeadingType { bool is_some; __swift_bridge__$AHRSHeadingType val; } __swift_bridge__$Option$AHRSHeadingType;

void* __swift_bridge__$Vec_AHRSHeadingType$new(void);
void __swift_bridge__$Vec_AHRSHeadingType$drop(void* vec_ptr);
void __swift_bridge__$Vec_AHRSHeadingType$push(void* vec_ptr, __swift_bridge__$AHRSHeadingType item);
__swift_bridge__$Option$AHRSHeadingType __swift_bridge__$Vec_AHRSHeadingType$pop(void* vec_ptr);
__swift_bridge__$Option$AHRSHeadingType __swift_bridge__$Vec_AHRSHeadingType$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$AHRSHeadingType __swift_bridge__$Vec_AHRSHeadingType$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_AHRSHeadingType$len(void* vec_ptr);
void* __swift_bridge__$Vec_AHRSHeadingType$as_ptr(void* vec_ptr);

typedef struct PreciseOwnship PreciseOwnship;
void __swift_bridge__$PreciseOwnship$_free(void* self);

void* __swift_bridge__$Vec_PreciseOwnship$new(void);
void __swift_bridge__$Vec_PreciseOwnship$drop(void* vec_ptr);
void __swift_bridge__$Vec_PreciseOwnship$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_PreciseOwnship$pop(void* vec_ptr);
void* __swift_bridge__$Vec_PreciseOwnship$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_PreciseOwnship$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_PreciseOwnship$len(void* vec_ptr);
void* __swift_bridge__$Vec_PreciseOwnship$as_ptr(void* vec_ptr);

typedef struct ForeFlightAHRS ForeFlightAHRS;
void __swift_bridge__$ForeFlightAHRS$_free(void* self);

void* __swift_bridge__$Vec_ForeFlightAHRS$new(void);
void __swift_bridge__$Vec_ForeFlightAHRS$drop(void* vec_ptr);
void __swift_bridge__$Vec_ForeFlightAHRS$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_ForeFlightAHRS$pop(void* vec_ptr);
void* __swift_bridge__$Vec_ForeFlightAHRS$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_ForeFlightAHRS$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_ForeFlightAHRS$len(void* vec_ptr);
void* __swift_bridge__$Vec_ForeFlightAHRS$as_ptr(void* vec_ptr);

typedef struct VerticalMetrics VerticalMetrics;
void __swift_bridge__$VerticalMetrics$_free(void* self);

void* __swift_bridge__$Vec_VerticalMetrics$new(void);
void __swift_bridge__$Vec_VerticalMetrics$drop(void* vec_ptr);
void __swift_bridge__$Vec_VerticalMetrics$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_VerticalMetrics$pop(void* vec_ptr);
void* __swift_bridge__$Vec_VerticalMetrics$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_VerticalMetrics$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_VerticalMetrics$len(void* vec_ptr);
void* __swift_bridge__$Vec_VerticalMetrics$as_ptr(void* vec_ptr);

typedef struct OwnshipGeometricAltitude OwnshipGeometricAltitude;
void __swift_bridge__$OwnshipGeometricAltitude$_free(void* self);

void* __swift_bridge__$Vec_OwnshipGeometricAltitude$new(void);
void __swift_bridge__$Vec_OwnshipGeometricAltitude$drop(void* vec_ptr);
void __swift_bridge__$Vec_OwnshipGeometricAltitude$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_OwnshipGeometricAltitude$pop(void* vec_ptr);
void* __swift_bridge__$Vec_OwnshipGeometricAltitude$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_OwnshipGeometricAltitude$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_OwnshipGeometricAltitude$len(void* vec_ptr);
void* __swift_bridge__$Vec_OwnshipGeometricAltitude$as_ptr(void* vec_ptr);

typedef struct TrafficReport TrafficReport;
void __swift_bridge__$TrafficReport$_free(void* self);

void* __swift_bridge__$Vec_TrafficReport$new(void);
void __swift_bridge__$Vec_TrafficReport$drop(void* vec_ptr);
void __swift_bridge__$Vec_TrafficReport$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_TrafficReport$pop(void* vec_ptr);
void* __swift_bridge__$Vec_TrafficReport$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_TrafficReport$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_TrafficReport$len(void* vec_ptr);
void* __swift_bridge__$Vec_TrafficReport$as_ptr(void* vec_ptr);

typedef struct HeightAboveTerrain HeightAboveTerrain;
void __swift_bridge__$HeightAboveTerrain$_free(void* self);

void* __swift_bridge__$Vec_HeightAboveTerrain$new(void);
void __swift_bridge__$Vec_HeightAboveTerrain$drop(void* vec_ptr);
void __swift_bridge__$Vec_HeightAboveTerrain$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_HeightAboveTerrain$pop(void* vec_ptr);
void* __swift_bridge__$Vec_HeightAboveTerrain$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_HeightAboveTerrain$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_HeightAboveTerrain$len(void* vec_ptr);
void* __swift_bridge__$Vec_HeightAboveTerrain$as_ptr(void* vec_ptr);

typedef struct Message Message;
void __swift_bridge__$Message$_free(void* self);

void* __swift_bridge__$Vec_Message$new(void);
void __swift_bridge__$Vec_Message$drop(void* vec_ptr);
void __swift_bridge__$Vec_Message$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Message$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Message$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Message$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Message$len(void* vec_ptr);
void* __swift_bridge__$Vec_Message$as_ptr(void* vec_ptr);

typedef struct MessageResult MessageResult;
void __swift_bridge__$MessageResult$_free(void* self);

void* __swift_bridge__$Vec_MessageResult$new(void);
void __swift_bridge__$Vec_MessageResult$drop(void* vec_ptr);
void __swift_bridge__$Vec_MessageResult$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_MessageResult$pop(void* vec_ptr);
void* __swift_bridge__$Vec_MessageResult$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_MessageResult$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_MessageResult$len(void* vec_ptr);
void* __swift_bridge__$Vec_MessageResult$as_ptr(void* vec_ptr);

typedef struct Velocity Velocity;
void __swift_bridge__$Velocity$_free(void* self);

void* __swift_bridge__$Vec_Velocity$new(void);
void __swift_bridge__$Vec_Velocity$drop(void* vec_ptr);
void __swift_bridge__$Vec_Velocity$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Velocity$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Velocity$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Velocity$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Velocity$len(void* vec_ptr);
void* __swift_bridge__$Vec_Velocity$as_ptr(void* vec_ptr);

typedef struct Length Length;
void __swift_bridge__$Length$_free(void* self);

void* __swift_bridge__$Vec_Length$new(void);
void __swift_bridge__$Vec_Length$drop(void* vec_ptr);
void __swift_bridge__$Vec_Length$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Length$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Length$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Length$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Length$len(void* vec_ptr);
void* __swift_bridge__$Vec_Length$as_ptr(void* vec_ptr);

typedef struct Angle Angle;
void __swift_bridge__$Angle$_free(void* self);

void* __swift_bridge__$Vec_Angle$new(void);
void __swift_bridge__$Vec_Angle$drop(void* vec_ptr);
void __swift_bridge__$Vec_Angle$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Angle$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Angle$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Angle$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Angle$len(void* vec_ptr);
void* __swift_bridge__$Vec_Angle$as_ptr(void* vec_ptr);

double __swift_bridge__$Angle$radians(void* self);
double __swift_bridge__$Angle$degrees(void* self);
double __swift_bridge__$Angle$seconds(void* self);
double __swift_bridge__$Angle$minutes(void* self);
double __swift_bridge__$Angle$revolutions(void* self);
double __swift_bridge__$Length$meters(void* self);
double __swift_bridge__$Length$kilometers(void* self);
double __swift_bridge__$Length$feet(void* self);
double __swift_bridge__$Length$nautical_miles(void* self);
double __swift_bridge__$Velocity$meters_per_second(void* self);
double __swift_bridge__$Velocity$kilometers_per_hour(void* self);
double __swift_bridge__$Velocity$feet_per_second(void* self);
double __swift_bridge__$Velocity$feet_per_minute(void* self);
double __swift_bridge__$Velocity$miles_per_hour(void* self);
double __swift_bridge__$Velocity$knots(void* self);
void* __swift_bridge__$parse_gdl90_bytes(struct __private__FfiSlice bytes);
bool __swift_bridge__$MessageResult$is_ok(void* self);
bool __swift_bridge__$MessageResult$is_err(void* self);
void* __swift_bridge__$MessageResult$ok(void* self);
void* __swift_bridge__$MessageResult$err(void* self);
struct __private__ResultPtrAndPtr __swift_bridge__$MessageResult$unwrap(void* self);
bool __swift_bridge__$Message$is_heartbeat(void* self);
bool __swift_bridge__$Message$is_initialization(void* self);
bool __swift_bridge__$Message$is_height_above_terrain(void* self);
bool __swift_bridge__$Message$is_ownship(void* self);
bool __swift_bridge__$Message$is_ownship_geometric_altitude(void* self);
bool __swift_bridge__$Message$is_traffic(void* self);
bool __swift_bridge__$Message$is_fore_flight_id(void* self);
bool __swift_bridge__$Message$is_fore_flight_ahrs(void* self);
bool __swift_bridge__$Message$is_precise_ownship(void* self);
struct __swift_bridge__$Option$Heartbeat __swift_bridge__$Message$heartbeat(void* self);
struct __swift_bridge__$Option$Initialization __swift_bridge__$Message$initialization(void* self);
void* __swift_bridge__$Message$height_above_terrain(void* self);
void* __swift_bridge__$Message$ownship(void* self);
void* __swift_bridge__$Message$traffic(void* self);
struct __swift_bridge__$TrafficAlertStatus __swift_bridge__$TrafficReport$traffic_alert_status(void* self);
struct __swift_bridge__$TargetIdentity __swift_bridge__$TrafficReport$target_identity(void* self);
void* __swift_bridge__$TrafficReport$latitude(void* self);
void* __swift_bridge__$TrafficReport$longitude(void* self);
void* __swift_bridge__$TrafficReport$altitude(void* self);
struct __swift_bridge__$MiscellaneousIndicators __swift_bridge__$TrafficReport$miscellaneous_indicators(void* self);
struct __swift_bridge__$NIC __swift_bridge__$TrafficReport$nic(void* self);
struct __swift_bridge__$NACp __swift_bridge__$TrafficReport$nacp(void* self);
void* __swift_bridge__$TrafficReport$horizontal_velocity(void* self);
void* __swift_bridge__$TrafficReport$vertical_velocity(void* self);
void* __swift_bridge__$TrafficReport$track_heading(void* self);
struct __swift_bridge__$EmitterCategory __swift_bridge__$TrafficReport$emitter_category(void* self);
void* __swift_bridge__$TrafficReport$callsign(void* self);
struct __swift_bridge__$EmergencyPriorityCode __swift_bridge__$TrafficReport$emergency_priority_code(void* self);
void* __swift_bridge__$Message$ownship_geometric_altitude(void* self);
void* __swift_bridge__$OwnshipGeometricAltitude$ownship_geo_altitude(void* self);
void* __swift_bridge__$OwnshipGeometricAltitude$vertical_metrics(void* self);
bool __swift_bridge__$VerticalMetrics$vertical_warning_indicator(void* self);
void* __swift_bridge__$VerticalMetrics$vfom(void* self);
struct __swift_bridge__$Option$ForeFlightID __swift_bridge__$Message$fore_flight_id(void* self);
void* __swift_bridge__$Message$fore_flight_ahrs(void* self);
void* __swift_bridge__$ForeFlightAHRS$roll(void* self);
void* __swift_bridge__$ForeFlightAHRS$pitch(void* self);
struct __swift_bridge__$AHRSHeadingType __swift_bridge__$ForeFlightAHRS$heading_type(void* self);
void* __swift_bridge__$ForeFlightAHRS$heading(void* self);
void* __swift_bridge__$ForeFlightAHRS$indicated_airspeed(void* self);
void* __swift_bridge__$ForeFlightAHRS$true_airspeed(void* self);
void* __swift_bridge__$Message$precise_ownship(void* self);
void* __swift_bridge__$PreciseOwnship$latitude(void* self);
void* __swift_bridge__$PreciseOwnship$longitude(void* self);
void* __swift_bridge__$PreciseOwnship$altitude(void* self);
void* __swift_bridge__$PreciseOwnship$ground_speed(void* self);
struct __swift_bridge__$NACp __swift_bridge__$to_nacp(uint8_t value);
struct __swift_bridge__$NIC __swift_bridge__$to_nic(uint8_t value);
uint8_t __swift_bridge__$from_nacp(struct __swift_bridge__$NACp nacp);
uint8_t __swift_bridge__$from_nic(struct __swift_bridge__$NIC nic);
void* __swift_bridge__$nacp_horizontal_accuracy(struct __swift_bridge__$NACp nacp);
void* __swift_bridge__$nacp_vertical_accuracy(struct __swift_bridge__$NACp nacp);


